#!/bin/sh

LINE=`grep guest $LIGHTDM_TEST_PASSWD_FILE`
if [ -z "$LINE" ] ; then
    echo "Error: guest account does not exist"
    exit 1
fi

# Remove account from password file
sed -i "/^guest:/c\\" $LIGHTDM_TEST_PASSWD_FILE

# Delete home directory
rm -rf $LIGHTDM_TEST_HOME_DIR/guest
