.\" Copyright (c) 2010 - Robert Ancell
.TH LIGHTDM 1 "27 June 2010"
.SH NAME
lightdm \- a display manager
.SH SYNOPSIS
.B lightdm
[
.I OPTION
]
.SH DESCRIPTION
.B lightdm
is a display manager.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help options
.TP
.B \-c, \-\-config=FILE
Use configuration file
.TP
.B \-d, \-\-debug
Print debugging messages
.TP
.B \-\-test\-mode
Run as unprivileged user, skipping things that require root access
.TP
.B \-\-pid\-file=FILE
File to write PID into
.TP
.B \-\-xsessions\-dir=DIRECTORY
Directory to load X sessions from
.TP
.B \-\-xgreeters\-dir=DIRECTORY
Directory to load X greeters from
.TP
.B \-\-log\-dir=DIRECTORY
Directory to write logs to
.TP
.B \-\-run\-dir=DIRECTORY
Directory to store running state
.TP
.B \-\-cache\-dir=DIRECTORY
Directory to cached information
.TP
.B \-v, \-\-version
Show release version
.SH FILES
.PD 0
.TP
.B /etc/lightdm/lightdm.conf
Configuration
.TP

.B /etc/lightdm/users.conf
User list configuration (if not using Accounts Service)
.TP

.B /etc/lightdm/keys.conf
XDMCP keys
.sp
.LP
