.\" Copyright (c) 2010 - Robert Ancell
.TH LIGHTDM 1 "27 June 2010"
.SH NAME
lightdm \- a display manager
.SH SYNOPSIS
.B lightdm
[
.I OPTION
] ...
.SH DESCRIPTION
.B lightdm
is a display manager.
.SH OPTIONS
.TP
.B \-c, \-\-config <file>
Use configuration file
.TP
.B \-d, \-\-debug
Print debugging messages
.TP
.B \-\-no\-root\-check
Don't check if root user
.TP
.B \-\-use\-session\-bus
Use the session D\-Bus
.TP
.B \-v, \-\-version
Show release version
.TP
.B \-h, \-\-help
Show help options
.SH FILES
.PD 0
.TP 18
.B /etc/lightdm.conf
Configuration
.sp
.LP
